// Full mapping: [greenStation][pinkStation] = { station: value, … }
export const valveSettings: Record<
  string,
  Record<string, Record<string, number>>
> = {
  Armory: {
    "Tank Factory": {
      Armory: 3,
      "Department Store": 2,
      Infirmary: 3,
      "Dragon Command": 1,
      "Supply Depot": 3,
    },
    "Department Store": {
      Armory: 1,
      "Supply Depot": 3,
      "Tank Factory": 1,
      Infirmary: 3,
      "Dragon Command": 2,
    },
    "Dragon Command": {
      Armory: 3,
      "Department Store": 2,
      Infirmary: 2,
      "Tank Factory": 2,
      "Supply Depot": 1,
    },
    "Supply Depot": {
      Armory: 2,
      "Tank Factory": 1,
      Infirmary: 1,
      "Department Store": 3,
      "Dragon Command": 1,
    },
    Infirmary: {
      Armory: 2,
      "Tank Factory": 2,
      "Supply Depot": 1,
      "Dragon Command": 2,
      "Department Store": 2,
    },
  },
  "Department Store": {
    Armory: {
      "Department Store": 3,
      "Dragon Command": 3,
      Infirmary: 2,
      "Tank Factory": 2,
      "Supply Depot": 2,
    },
    "Dragon Command": {
      "Department Store": 2,
      Infirmary: 2,
      "Tank Factory": 3,
      Armory: 1,
      "Supply Depot": 1,
    },
    "Supply Depot": {
      "Department Store": 1,
      Armory: 2,
      "Tank Factory": 1,
      Infirmary: 3,
      "Dragon Command": 1,
    },
    Infirmary: {
      "Department Store": 1,
      Armory: 2,
      "Tank Factory": 2,
      "Supply Depot": 1,
      "Dragon Command": 3,
    },
    "Tank Factory": {
      "Department Store": 2,
      Infirmary: 3,
      "Dragon Command": 1,
      "Supply Depot": 2,
      Armory: 2,
    },
  },
  "Dragon Command": {
    "Supply Depot": {
      "Dragon Command": 2,
      "Department Store": 2,
      Infirmary: 2,
      "Tank Factory": 3,
      Armory: 1,
    },
    Infirmary: {
      "Dragon Command": 1,
      "Supply Depot": 3,
      "Tank Factory": 3,
      Armory: 3,
      "Department Store": 2,
    },
    "Tank Factory": {
      "Dragon Command": 3,
      Infirmary: 1,
      "Department Store": 1,
      Armory: 1,
      "Supply Depot": 3,
    },
    "Department Store": {
      "Dragon Command": 1,
      "Supply Depot": 2,
      Armory: 2,
      "Tank Factory": 1,
      Infirmary: 1,
    },
    Armory: {
      "Dragon Command": 1,
      "Supply Depot": 3,
      "Tank Factory": 1,
      Infirmary: 1,
      "Department Store": 1,
    },
  },
  "Supply Depot": {
    Infirmary: {
      "Supply Depot": 3,
      "Tank Factory": 3,
      Armory: 3,
      "Department Store": 3,
      "Dragon Command": 3,
    },
    "Tank Factory": {
      "Supply Depot": 2,
      Armory: 3,
      "Department Store": 3,
      "Dragon Command": 3,
      Infirmary: 2,
    },
    "Dragon Command": {
      "Supply Depot": 3,
      "Tank Factory": 3,
      Armory: 3,
      "Department Store": 2,
      Infirmary: 3,
    },
    "Department Store": {
      "Supply Depot": 2,
      Armory: 2,
      "Tank Factory": 1,
      Infirmary: 3,
      "Dragon Command": 2,
    },
    Armory: {
      "Supply Depot": 3,
      "Tank Factory": 1,
      Infirmary: 3,
      "Dragon Command": 2,
      "Department Store": 1,
    },
  },
  Infirmary: {
    "Tank Factory": {
      Infirmary: 3,
      "Dragon Command": 2,
      "Department Store": 1,
      Armory: 1,
      "Supply Depot": 3,
    },
    "Supply Depot": {
      Infirmary: 3,
      "Dragon Command": 2,
      "Department Store": 1,
      Armory: 2,
      "Tank Factory": 2,
    },
    "Dragon Command": {
      Infirmary: 2,
      "Tank Factory": 2,
      "Supply Depot": 2,
      Armory: 3,
      "Department Store": 3,
    },
    "Department Store": {
      Infirmary: 3,
      "Dragon Command": 1,
      "Supply Depot": 3,
      "Tank Factory": 3,
      Armory: 3,
    },
    Armory: {
      Infirmary: 2,
      "Tank Factory": 2,
      "Supply Depot": 1,
      "Dragon Command": 2,
      "Department Store": 1,
    },
  },
  "Tank Factory": {
    Infirmary: {
      "Tank Factory": 2,
      "Supply Depot": 2,
      Armory: 3,
      "Department Store": 3,
      "Dragon Command": 3,
    },
    "Supply Depot": {
      "Tank Factory": 1,
      Infirmary: 3,
      "Dragon Command": 2,
      "Department Store": 1,
      Armory: 1,
    },
    "Dragon Command": {
      "Tank Factory": 1,
      Infirmary: 1,
      "Department Store": 1,
      Armory: 1,
      "Supply Depot": 1,
    },
    "Department Store": {
      "Tank Factory": 1,
      Infirmary: 3,
      "Dragon Command": 1,
      "Supply Depot": 2,
      Armory: 3,
    },
    Armory: {
      "Tank Factory": 1,
      Infirmary: 1,
      "Department Store": 3,
      "Dragon Command": 1,
      "Supply Depot": 2,
    },
  },
};
